version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "Fretes"
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - minha-rede

  azchip-fretes:
    container_name: azchip-fretes
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/Fretes
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge

volumes:
  pgdata: