version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "usuarios"
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - minha-rede

  # crud-aplication:
  #   container_name: azchip-fretes
  #   image: jesriel/azchip-fretes
  #   environment:
  #     - DB_URL=jdbc:postgresql://postgres:5432/usuarios
  #   volumes:
  #     - ./application.yml:/app/application.yml
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - minha-rede

networks:
  minha-rede:
    driver: bridge
volumes:
  pgdata: